services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: devenvcpp-raccoon-x86_64-image:latest
    command: sleep infinity
    volumes:
      - ../..:/workspace:cached
      - build_dir:/build
volumes:
  build_dir: